# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\projects\update_maker\depo_daily_report\design_pyqt.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(713, 100)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_1 = QtWidgets.QLabel(self.centralwidget)
        self.label_1.setGeometry(QtCore.QRect(10, 10, 61, 16))
        self.label_1.setObjectName("label_1")
        self.button_start = QtWidgets.QPushButton(self.centralwidget)
        self.button_start.setGeometry(QtCore.QRect(640, 70, 61, 21))
        self.button_start.setObjectName("button_start")
        self.line_base = QtWidgets.QLineEdit(self.centralwidget)
        self.line_base.setGeometry(QtCore.QRect(80, 70, 111, 20))
        self.line_base.setObjectName("line_base")
        self.line_user = QtWidgets.QLineEdit(self.centralwidget)
        self.line_user.setGeometry(QtCore.QRect(280, 70, 181, 20))
        self.line_user.setObjectName("line_user")
        self.line_pass = QtWidgets.QLineEdit(self.centralwidget)
        self.line_pass.setGeometry(QtCore.QRect(540, 70, 91, 20))
        self.line_pass.setText("")
        self.line_pass.setEchoMode(QtWidgets.QLineEdit.Password)
        self.line_pass.setObjectName("line_pass")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(10, 70, 61, 16))
        self.label_4.setObjectName("label_4")
        self.combo_why = QtWidgets.QComboBox(self.centralwidget)
        self.combo_why.setGeometry(QtCore.QRect(80, 40, 111, 22))
        self.combo_why.setObjectName("combo_why")
        self.combo_why.addItem("")
        self.combo_why.addItem("")
        self.combo_why.addItem("")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(10, 40, 61, 16))
        self.label_2.setObjectName("label_2")
        self.date_report = QtWidgets.QDateEdit(self.centralwidget)
        self.date_report.setGeometry(QtCore.QRect(80, 10, 110, 22))
        self.date_report.setObjectName("date_report")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(200, 70, 81, 16))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(470, 70, 41, 16))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(200, 40, 71, 16))
        self.label_7.setObjectName("label_7")
        self.line_path = QtWidgets.QLineEdit(self.centralwidget)
        self.line_path.setGeometry(QtCore.QRect(280, 40, 181, 20))
        self.line_path.setText("")
        self.line_path.setObjectName("line_path")
        self.button_path = QtWidgets.QPushButton(self.centralwidget)
        self.button_path.setGeometry(QtCore.QRect(470, 40, 61, 21))
        self.button_path.setObjectName("button_path")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(470, 10, 61, 16))
        self.label_3.setObjectName("label_3")
        self.combo_sign = QtWidgets.QComboBox(self.centralwidget)
        self.combo_sign.setGeometry(QtCore.QRect(540, 10, 161, 22))
        self.combo_sign.setObjectName("combo_sign")
        self.combo_why_action = QtWidgets.QComboBox(self.centralwidget)
        self.combo_why_action.setGeometry(QtCore.QRect(280, 10, 181, 22))
        self.combo_why_action.setObjectName("combo_why_action")
        self.combo_why_action.addItem("")
        self.combo_why_action.addItem("")
        self.combo_why_action.addItem("")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(200, 10, 71, 16))
        self.label_8.setObjectName("label_8")
        self.checkbox_if_nulls = QtWidgets.QCheckBox(self.centralwidget)
        self.checkbox_if_nulls.setGeometry(QtCore.QRect(540, 40, 171, 18))
        self.checkbox_if_nulls.setObjectName("checkbox_if_nulls")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Экспорт ежедневных отчётов ДЕПО"))
        self.label_1.setText(_translate("MainWindow", "Дата:"))
        self.button_start.setText(_translate("MainWindow", "Start"))
        self.line_base.setText(_translate("MainWindow", "XXI"))
        self.label_4.setText(_translate("MainWindow", "База:"))
        self.combo_why.setItemText(0, _translate("MainWindow", "Всё"))
        self.combo_why.setItemText(1, _translate("MainWindow", "Остатки"))
        self.combo_why.setItemText(2, _translate("MainWindow", "Операции"))
        self.label_2.setText(_translate("MainWindow", "Выгружать:"))
        self.label_5.setText(_translate("MainWindow", "Пользователь:"))
        self.label_6.setText(_translate("MainWindow", "Пароль:"))
        self.label_7.setText(_translate("MainWindow", "Директория:"))
        self.button_path.setText(_translate("MainWindow", "Open"))
        self.label_3.setText(_translate("MainWindow", "Подписант:"))
        self.combo_why_action.setItemText(0, _translate("MainWindow", "Сформировать и выгрузить"))
        self.combo_why_action.setItemText(1, _translate("MainWindow", "Сформировать"))
        self.combo_why_action.setItemText(2, _translate("MainWindow", "Выгрузить"))
        self.label_8.setText(_translate("MainWindow", "Что сделать:"))
        self.checkbox_if_nulls.setText(_translate("MainWindow", "Включать нулевые остатки"))
