# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\projects\update_maker\SQL_utility\design.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(850, 320)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(850, 320))
        MainWindow.setMaximumSize(QtCore.QSize(850, 320))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_1 = QtWidgets.QLabel(self.centralwidget)
        self.label_1.setGeometry(QtCore.QRect(210, 40, 71, 21))
        self.label_1.setObjectName("label_1")
        self.button_start = QtWidgets.QPushButton(self.centralwidget)
        self.button_start.setGeometry(QtCore.QRect(510, 290, 131, 21))
        self.button_start.setObjectName("button_start")
        self.line_base = QtWidgets.QLineEdit(self.centralwidget)
        self.line_base.setGeometry(QtCore.QRect(40, 290, 61, 20))
        self.line_base.setObjectName("line_base")
        self.line_user = QtWidgets.QLineEdit(self.centralwidget)
        self.line_user.setGeometry(QtCore.QRect(190, 290, 121, 20))
        self.line_user.setObjectName("line_user")
        self.line_pass = QtWidgets.QLineEdit(self.centralwidget)
        self.line_pass.setGeometry(QtCore.QRect(370, 290, 131, 20))
        self.line_pass.setText("")
        self.line_pass.setEchoMode(QtWidgets.QLineEdit.Password)
        self.line_pass.setObjectName("line_pass")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(10, 290, 31, 21))
        self.label_4.setObjectName("label_4")
        self.combo_why = QtWidgets.QComboBox(self.centralwidget)
        self.combo_why.setGeometry(QtCore.QRect(90, 10, 111, 22))
        self.combo_why.setObjectName("combo_why")
        self.combo_why.addItem("")
        self.combo_why.addItem("")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(10, 10, 71, 21))
        self.label_2.setObjectName("label_2")
        self.date_from = QtWidgets.QDateEdit(self.centralwidget)
        self.date_from.setGeometry(QtCore.QRect(290, 40, 110, 22))
        self.date_from.setObjectName("date_from")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(110, 290, 81, 21))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(320, 290, 41, 21))
        self.label_6.setObjectName("label_6")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(440, 40, 91, 21))
        self.label_3.setObjectName("label_3")
        self.date_to = QtWidgets.QDateEdit(self.centralwidget)
        self.date_to.setGeometry(QtCore.QRect(540, 40, 101, 22))
        self.date_to.setObjectName("date_to")
        self.combo_sql = QtWidgets.QComboBox(self.centralwidget)
        self.combo_sql.setGeometry(QtCore.QRect(290, 10, 351, 22))
        self.combo_sql.setObjectName("combo_sql")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(210, 10, 71, 21))
        self.label_7.setObjectName("label_7")
        self.table_param_basic = QtWidgets.QTableWidget(self.centralwidget)
        self.table_param_basic.setGeometry(QtCore.QRect(10, 70, 631, 181))
        self.table_param_basic.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.table_param_basic.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.table_param_basic.setObjectName("table_param_basic")
        self.table_param_basic.setColumnCount(2)
        self.table_param_basic.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        item.setFont(font)
        self.table_param_basic.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.table_param_basic.setHorizontalHeaderItem(1, item)
        self.table_param_basic.horizontalHeader().setCascadingSectionResizes(False)
        self.table_param_basic.horizontalHeader().setDefaultSectionSize(250)
        self.table_param_basic.horizontalHeader().setHighlightSections(True)
        self.table_param_basic.horizontalHeader().setSortIndicatorShown(True)
        self.table_param_basic.horizontalHeader().setStretchLastSection(True)
        self.table_param_basic.verticalHeader().setVisible(True)
        self.table_param_basic.verticalHeader().setCascadingSectionResizes(False)
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(10, 40, 111, 21))
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(650, 10, 211, 16))
        self.label_9.setObjectName("label_9")
        self.text_param_addit = QtWidgets.QTextEdit(self.centralwidget)
        self.text_param_addit.setGeometry(QtCore.QRect(650, 30, 191, 281))
        self.text_param_addit.setObjectName("text_param_addit")
        self.line_path = QtWidgets.QLineEdit(self.centralwidget)
        self.line_path.setGeometry(QtCore.QRect(110, 260, 391, 20))
        self.line_path.setText("")
        self.line_path.setObjectName("line_path")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(10, 260, 101, 21))
        self.label_10.setObjectName("label_10")
        self.button_open = QtWidgets.QPushButton(self.centralwidget)
        self.button_open.setGeometry(QtCore.QRect(510, 260, 131, 21))
        self.button_open.setObjectName("button_open")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Утилита для работы с ПО ФОНД"))
        self.label_1.setText(_translate("MainWindow", "Дата начала:"))
        self.button_start.setText(_translate("MainWindow", "Start"))
        self.line_base.setText(_translate("MainWindow", "XXI"))
        self.line_user.setText(_translate("MainWindow", "BROKER"))
        self.label_4.setText(_translate("MainWindow", "База:"))
        self.combo_why.setItemText(0, _translate("MainWindow", "Выполнить"))
        self.combo_why.setItemText(1, _translate("MainWindow", "Выгрузить"))
        self.label_2.setText(_translate("MainWindow", "Что сделать:"))
        self.label_5.setText(_translate("MainWindow", "Пользователь:"))
        self.label_6.setText(_translate("MainWindow", "Пароль:"))
        self.label_3.setText(_translate("MainWindow", "Дата окончания:"))
        self.label_7.setText(_translate("MainWindow", "Скрипт:"))
        item = self.table_param_basic.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Параметр"))
        item = self.table_param_basic.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Значение"))
        self.label_8.setText(_translate("MainWindow", "Входные параметры:"))
        self.label_9.setText(_translate("MainWindow", "Дополнительные параметры отбора:"))
        self.text_param_addit.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'MS Shell Dlg 2\';\"><br /></p></body></html>"))
        self.label_10.setText(_translate("MainWindow", "Выгрузить в файл:"))
        self.button_open.setText(_translate("MainWindow", "Open"))
