# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(560, 391)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.fix_date = QtWidgets.QDateEdit(self.centralwidget)
        self.fix_date.setGeometry(QtCore.QRect(160, 10, 110, 22))
        self.fix_date.setObjectName("fix_date")
        self.label_1 = QtWidgets.QLabel(self.centralwidget)
        self.label_1.setGeometry(QtCore.QRect(20, 10, 101, 16))
        self.label_1.setObjectName("label_1")
        self.nrd_date = QtWidgets.QDateEdit(self.centralwidget)
        self.nrd_date.setGeometry(QtCore.QRect(160, 50, 110, 22))
        self.nrd_date.setObjectName("nrd_date")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(20, 50, 131, 16))
        self.label_2.setObjectName("label_2")
        self.list_type = QtWidgets.QComboBox(self.centralwidget)
        self.list_type.setGeometry(QtCore.QRect(160, 90, 101, 22))
        self.list_type.setObjectName("list_type")
        self.list_type.addItem("")
        self.list_type.addItem("")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(20, 90, 131, 16))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(20, 130, 131, 16))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(20, 161, 131, 16))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(20, 190, 131, 16))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(20, 220, 131, 16))
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(20, 250, 121, 16))
        self.label_8.setObjectName("label_8")
        self.exp_dir = QtWidgets.QLineEdit(self.centralwidget)
        self.exp_dir.setGeometry(QtCore.QRect(160, 250, 241, 20))
        self.exp_dir.setObjectName("exp_dir")
        self.button_path = QtWidgets.QPushButton(self.centralwidget)
        self.button_path.setGeometry(QtCore.QRect(410, 250, 61, 21))
        self.button_path.setObjectName("button_path")
        self.line_pass = QtWidgets.QLineEdit(self.centralwidget)
        self.line_pass.setGeometry(QtCore.QRect(420, 290, 111, 20))
        self.line_pass.setObjectName("line_pass")
        self.line_user = QtWidgets.QLineEdit(self.centralwidget)
        self.line_user.setGeometry(QtCore.QRect(250, 290, 111, 20))
        self.line_user.setObjectName("line_user")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(370, 290, 41, 16))
        self.label_9.setObjectName("label_9")
        self.button_start = QtWidgets.QPushButton(self.centralwidget)
        self.button_start.setGeometry(QtCore.QRect(590, 290, 61, 21))
        self.button_start.setObjectName("button_start")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(20, 290, 61, 16))
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(170, 290, 81, 16))
        self.label_11.setObjectName("label_11")
        self.line_base = QtWidgets.QLineEdit(self.centralwidget)
        self.line_base.setGeometry(QtCore.QRect(50, 290, 111, 20))
        self.line_base.setObjectName("line_base")
        self.ref_kd = QtWidgets.QLineEdit(self.centralwidget)
        self.ref_kd.setGeometry(QtCore.QRect(160, 130, 241, 20))
        self.ref_kd.setObjectName("ref_kd")
        self.nrd_notice = QtWidgets.QLineEdit(self.centralwidget)
        self.nrd_notice.setGeometry(QtCore.QRect(160, 160, 241, 20))
        self.nrd_notice.setObjectName("nrd_notice")
        self.isin_list = QtWidgets.QLineEdit(self.centralwidget)
        self.isin_list.setGeometry(QtCore.QRect(160, 190, 241, 20))
        self.isin_list.setObjectName("isin_list")
        self.storage_list = QtWidgets.QLineEdit(self.centralwidget)
        self.storage_list.setGeometry(QtCore.QRect(160, 220, 241, 20))
        self.storage_list.setObjectName("storage_list")
        self.button_start_2 = QtWidgets.QPushButton(self.centralwidget)
        self.button_start_2.setGeometry(QtCore.QRect(250, 330, 61, 21))
        self.button_start_2.setObjectName("button_start_2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 560, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Распоряжение по сбору списка"))
        self.label_1.setText(_translate("MainWindow", "Дата фиксации:"))
        self.label_2.setText(_translate("MainWindow", "Дата уведомления НРД:"))
        self.list_type.setItemText(0, _translate("MainWindow", "OWNL"))
        self.list_type.setItemText(1, _translate("MainWindow", "AUTL"))
        self.label_3.setText(_translate("MainWindow", "Тип списка"))
        self.label_4.setText(_translate("MainWindow", "Референс КД"))
        self.label_5.setText(_translate("MainWindow", "Уведомление НРД"))
        self.label_6.setText(_translate("MainWindow", "Бумага"))
        self.label_7.setText(_translate("MainWindow", "Место хранения"))
        self.label_8.setText(_translate("MainWindow", "Директория экспорта:"))
        self.button_path.setText(_translate("MainWindow", "Open"))
        self.label_9.setText(_translate("MainWindow", "Пароль:"))
        self.button_start.setText(_translate("MainWindow", "Start"))
        self.label_10.setText(_translate("MainWindow", "База:"))
        self.label_11.setText(_translate("MainWindow", "Пользователь:"))
        self.button_start_2.setText(_translate("MainWindow", "Start"))
